variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet_az1_cidr" {}
variable "private_subnet_az2_cidr" {}
variable "private_subnet_az3_cidr" {}
variable "private_subnet_az4_cidr" {}
variable "instance_type" {}
variable "ami_id" {}
variable "db_name" {}
variable "db_instance_class" {}
variable "db_allocated_storage" {}
